<?php

use Illuminate\Database\Seeder;

class RawDataSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(){

        DB::statement("INSERT INTO `users` (`id`, `name`, `email`, `email_verified_at`, `password`, `remember_token`, `created_at`, `updated_at`) VALUES
        (1, 'Test User', 'test@test.com', NULL, '$2y$10$3jyAN.e/uliEHv5KJMBA2O3DeFw2MHZgeAmPVeDvDmpkxTDH4mW/i', NULL, '2021-04-06 09:09:35', '2021-04-06 09:09:35');");

        DB::statement("INSERT INTO `listings` (`id`, `user_id`, `category_id`, `location_code`, `title`, `description`, `excerpt`, `price`, `currency`, `slug`, `status`, `last_date_online`, `last_date_offline`, `created_at`, `updated_at`, `views`) VALUES
        (1, 1, 2, 'LA', 'Mercedes-Benz C300 2016 Black', 'Pristine clean foreign used foreign used c300 2016 full option at giveaway price. reason for selling that cheap: owner wants to swap for a higher mercedes-benz. don’t sleep on this offer. a dealer can buy and resell.', 'Pristine clean foreign used foreign used c300 2016 full option at giveaway price. reason for selling that cheap: owner wants to swap for a higher mercedes-benz. don’t sleep on this offer. a dealer can buy and resell.', '8500000.00', 'NGN', 'mercedes-benz-c300-2016-black-1', 'online', NULL, NULL, '2021-04-06 09:43:20', '2021-04-06 10:23:02', 0),
        (2, 1, 2, 'LA', 'Land Rover Range Rover Evoque 2013 Black', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae.', '8200000.00', 'NGN', 'land-rover-range-rover-evoque-2013-black-2', 'online', NULL, NULL, '2021-04-06 09:50:09', '2021-04-06 10:23:00', 0),
        (3, 1, 2, 'LA', 'Toyota Avalon 2014 Gold', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique', '5750000.00', 'NGN', 'toyota-avalon-2014-gold-3', 'online', NULL, NULL, '2021-04-06 10:00:11', '2021-04-06 10:22:57', 0),
        (4, 1, 9, 'LA', 'Mini-Flat Apartment for Rent', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique', '500000.00', 'NGN', 'mini-flat-apartment-for-rent-4', 'online', NULL, NULL, '2021-04-06 10:17:57', '2021-04-06 10:18:12', 0),
        (5, 1, 9, 'LA', '3 Bedroom Luxury Duplex at Lifecamp for Sale', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique.', '2990000.00', 'NGN', '3-bedroom-luxury-duplex-at-lifecamp-for-sale-5', 'online', NULL, NULL, '2021-04-06 10:22:30', '2021-04-06 10:22:55', 0),
        (6, 1, 7, 'LA', 'Set of Chair', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique.', '80000.00', 'NGN', 'set-of-chair-6', 'online', NULL, NULL, '2021-04-06 10:30:46', '2021-04-06 10:30:54', 0),
        (7, 1, 5, 'LA', 'Evening Dress', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique.', '40000.00', 'NGN', 'evening-dress-7', 'online', NULL, NULL, '2021-04-06 10:33:44', '2021-04-06 10:33:48', 0),
        (8, 1, 5, 'LA', 'Balmain Sneakers', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique. Praesent tincidunt mi lectus, ut pretium nibh efficitur vitae. Sed malesuada ligula at diam ornare, non varius lacus consequat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. In vel lacus ac nisl iaculis suscipit. In erat sem, facilisis non ultricies ac, laoreet eu nibh.\n\nNulla ultricies purus sed congue eleifend. Vivamus pretium dui ac est porta, blandit mattis libero commodo. Integer sagittis placerat viverra. Phasellus orci lorem, aliquam eu luctus in, consectetur id purus. Sed semper eu justo nec gravida. Vestibulum malesuada eu libero non viverra. Fusce posuere justo non tellus congue, vel facilisis augue faucibus.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc egestas vel velit et ultrices. Nullam auctor bibendum ante rutrum tristique.', '59000.00', 'NGN', 'balmain-sneakers-8', 'online', NULL, NULL, '2021-04-06 10:38:52', '2021-04-06 10:38:57', 0);");
    }
}
