version: '2'
services:
  app:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file: .env
    working_dir: /app
    command: sh -c ' ./wait-for-it.sh database:3306 -- php artisan key:gen && php artisan migrate && php artisan passport:install && php artisan db:seed && php artisan serve --host 0.0.0.0'
    environment: 
      DB_CONNECTION: mysql
      DB_HOST: database
      DB_PORT: 3306
      DB_DATABASE: classified
      DB_USERNAME: db_user
      DB_PASSWORD: thyword123
    depends_on:
      - db
    links:
      - db
    networks:
    - app-network

  db:
    image: "mysql:5.7"
    container_name: database
    environment:
      - MYSQL_ROOT_PASSWORD=testpasword
      - MYSQL_DATABASE=classified
      - MYSQL_USER=db_user
      - MYSQL_PASSWORD=thyword123
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
    - app-network

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8090:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: "testpasword"
    networks:
    - app-network

#Docker Networks
networks:
  app-network:
    driver: bridge